name: Continuous Integration

on:
  push:
    branches: [ main, Karan, feature-verify ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: "Frontend - Mishal's Lab/Frontend/User"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: "Frontend - Mishal's Lab/Frontend/User/package-lock.json"

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build project
      run: npm run build --if-present

    - name: Run Cypress E2E Tests
      uses: cypress-io/github-action@v6
      with:
        working-directory: "Frontend - Mishal's Lab/Frontend/User"
        start: npx serve -s build -l 3002 --no-port-switching
        wait-on: "http://localhost:3002"
        wait-on-timeout: 120
